stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Train.csv
    outs:
    - data/raw/Train.csv

  preprocessed_data:
    cmd: python src/preprocessed_data.py --config=params.yaml
    deps:
    - src/preprocessed_data.py
    - data/raw/Train.csv
    outs:
    - data/processed/processed_Train.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/processed/processed_Train.csv
    outs:
    - data/processed/train_data.csv
    - data/processed/test_data.csv