base:
  project: StoreSalesPrediction-project
  random_state: 42
  target_col: Item_Outlet_Sales

data_source:
  s3_source: data_given/Train.csv

load_data:
  raw_dataset_csv: data/raw/Train.csv

preprocessed_data:
  preprocessed_data_csv: data/processed/processed_Train.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      n_estimators: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200]
      max_features: [1.0,'sqrt']
      max_depth: [5, 10, 15, 20, 25, 30]
      min_samples_split: [2, 5, 10, 15, 100]
      min_samples_leaf: [1, 2, 5, 10]
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib